### ISSUE TITLE
NAs  error

### ISSUE THREAD

**Issue by afshinmoradi** [plevritis-lab/CELESTA#12]
Dear,

I got this error
Do you have any idea how to fix it 

Your help is appreciated .

Best regards

Error in current_scoring_matrix[unassigned_cells, cell_type_num[i]] <- GetScore(activation_prob_to_use,  : 
  NAs are not allowed in subscripted assignments
In addition: Warning messages:
1: In lineage_info$Cell_type_number == previous_level_type :
  longer object length is not a multiple of shorter object length
2: In current_cell_type_assignment[, previous_level_round] == previous_level_type :
  longer object length is not a multiple of shorter object length

**Comment by andrewjUTSW** [comment]
Hi there! I think I also encountered this. 
And I think I may have fixed the issue with this pull request: https://github.com/plevritis-lab/CELESTA/pull/11 
You can check my forked repo for the corrected code: https://github.com/andrewjUTSW/CELESTA

**Comment by afshinmoradi** [comment]
Thanks for that

**Comment by weiruo16** [comment]
Hi, we have fixed the issue with empty unassigned cells in the main branch.  Please try it again. In addition, the warning messages may indicate that the input cell-type signature has some formatting errors, which may actually cause the error.

**Comment by matthew-lee1** [comment]
Hello, 

I have recently installed the latest version of CELESTA and am still getting the following error: 

```
Error in current_scoring_matrix[unassigned_cells, cell_type_num[i]] <- GetScore(activation_prob_to_use,  : 
  NAs are not allowed in subscripted assignments
In addition: Warning message:
In lineage_info$Cell_type_number == previous_level_type :
  longer object length is not a multiple of shorter object length
```

If needed i can provide code, however it is essentially identical to the code given in README.
